### PR TITLE
Fix newlines in db setup

### PR DESCRIPTION
**Pull request by muralithiyagarajan**

### CODE REVIEW

**Comment by erssebaggala** [comment]
The fix for the newlines is not there in the changes!!

**Comment by erssebaggala** [comment]
I believe git is forcing windows style newlines. This warning is shown on commit: "LF will be replaced by CRLF". We will investigate further.

**Comment by muralithiyagarajan** [comment]
similar issues is in **queue_setup.sh** also

**Comment by erssebaggala** [comment]
For now, the release management scripts correct this in the final release archive publised. See the links at the link below:

https://github.com/bodastage/bts-ce-release/blob/master/create_package.sh#L29-L30

**Pull request merged**
